/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImageMarkdownPastePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  imageSavePath: "attachments/{filename}",
  useStandardMarkdown: true,
  autoRenameOnConflict: true,
  enableRenameSync: true,
  enableMoveSync: true
};
var ImageMarkdownPasteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Image Markdown Paste \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u56FE\u7247\u4FDD\u5B58\u8DEF\u5F84").setDesc(this.createPathDescription()).addText((text) => text.setPlaceholder("attachments/{filename}").setValue(this.plugin.settings.imageSavePath).onChange(async (value) => {
      this.plugin.settings.imageSavePath = value || DEFAULT_SETTINGS.imageSavePath;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u4F7F\u7528\u6807\u51C6 Markdown \u683C\u5F0F").setDesc("\u542F\u7528\u540E\uFF0C\u56FE\u7247\u5F15\u7528\u5C06\u4F7F\u7528\u6807\u51C6\u7684 Markdown \u683C\u5F0F ![alt](path)\uFF0C\u800C\u4E0D\u662F WikiLink \u683C\u5F0F [[path]]").addToggle((toggle) => toggle.setValue(this.plugin.settings.useStandardMarkdown).onChange(async (value) => {
      this.plugin.settings.useStandardMarkdown = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6587\u4EF6\u540D\u51B2\u7A81\u65F6\u81EA\u52A8\u91CD\u547D\u540D").setDesc("\u5F53\u76EE\u6807\u4F4D\u7F6E\u5DF2\u5B58\u5728\u540C\u540D\u6587\u4EF6\u65F6\uFF0C\u81EA\u52A8\u6DFB\u52A0\u5E8F\u53F7\u91CD\u547D\u540D").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoRenameOnConflict).onChange(async (value) => {
      this.plugin.settings.autoRenameOnConflict = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u91CD\u547D\u540D\u540C\u6B65").setDesc("\u5F53\u6587\u6863\u91CD\u547D\u540D\u65F6\uFF0C\u81EA\u52A8\u540C\u6B65\u91CD\u547D\u540D\u6587\u6863\u4E2D\u5F15\u7528\u7684\u56FE\u7247\uFF08\u4EC5\u5F53\u8DEF\u5F84\u5305\u542B {filename} \u53D8\u91CF\u65F6\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableRenameSync).onChange(async (value) => {
      this.plugin.settings.enableRenameSync = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u79FB\u52A8\u540C\u6B65").setDesc("\u5F53\u6587\u6863\u79FB\u52A8\u5230\u5176\u4ED6\u4F4D\u7F6E\u65F6\uFF0C\u81EA\u52A8\u5C06\u76F8\u5173\u56FE\u7247\u79FB\u52A8\u5230\u66F4\u65B0\u540E\u7684\u4F4D\u7F6E").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMoveSync).onChange(async (value) => {
      this.plugin.settings.enableMoveSync = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u53EF\u7528\u53D8\u91CF" });
    const varList = containerEl.createEl("ul");
    const variables = [
      { name: "{filename}", desc: "\u5F53\u524D\u6587\u6863\u7684\u6587\u4EF6\u540D\uFF08\u4E0D\u542B\u6269\u5C55\u540D\uFF09" },
      { name: "{filepath}", desc: "\u5F53\u524D\u6587\u6863\u7684\u5B8C\u6574\u8DEF\u5F84\uFF08\u4E0D\u542B\u6269\u5C55\u540D\uFF09" },
      { name: "{folder}", desc: "\u5F53\u524D\u6587\u6863\u6240\u5728\u6587\u4EF6\u5939\u540D\u79F0" },
      { name: "{folderpath}", desc: "\u5F53\u524D\u6587\u6863\u6240\u5728\u6587\u4EF6\u5939\u7684\u5B8C\u6574\u8DEF\u5F84" },
      { name: "{date}", desc: "\u5F53\u524D\u65E5\u671F\uFF08YYYYMMDD\uFF09" },
      { name: "{time}", desc: "\u5F53\u524D\u65F6\u95F4\uFF08HHmmss\uFF09" },
      { name: "{datetime}", desc: "\u5F53\u524D\u65E5\u671F\u65F6\u95F4\uFF08YYYYMMDD-HHmmss\uFF09" },
      { name: "{year}", desc: "\u5F53\u524D\u5E74\u4EFD" },
      { name: "{month}", desc: "\u5F53\u524D\u6708\u4EFD" },
      { name: "{day}", desc: "\u5F53\u524D\u65E5\u671F" }
    ];
    variables.forEach((v) => {
      const li = varList.createEl("li");
      li.createEl("code", { text: v.name });
      li.appendText(` - ${v.desc}`);
    });
  }
  createPathDescription() {
    const frag = document.createDocumentFragment();
    frag.appendText("\u8BBE\u7F6E\u7C98\u8D34\u56FE\u7247\u7684\u4FDD\u5B58\u8DEF\u5F84\uFF0C\u652F\u6301\u4F7F\u7528\u53D8\u91CF\u3002\u4F8B\u5982\uFF1A");
    frag.appendChild(document.createElement("br"));
    const code = frag.createEl("code", { text: "attachments/{filename}" });
    code.style.backgroundColor = "var(--background-modifier-hover)";
    code.style.padding = "2px 4px";
    code.style.borderRadius = "4px";
    frag.appendText(" \u4F1A\u5C06\u56FE\u7247\u4FDD\u5B58\u5230\u4E0E\u6587\u6863\u540C\u540D\u7684\u5B50\u6587\u4EF6\u5939\u4E2D");
    return frag;
  }
};

// utils.ts
var import_obsidian2 = require("obsidian");
function parsePathTemplate(template, sourceFile) {
  const now = (0, import_obsidian2.moment)();
  const parent = sourceFile.parent;
  const folderPath = parent ? parent.path : "";
  const folderName = parent ? parent.name : "";
  const filePathWithoutExt = sourceFile.path.replace(/\.[^/.]+$/, "");
  const fileNameWithoutExt = sourceFile.basename;
  let result = template;
  const variables = {
    "{filename}": fileNameWithoutExt,
    "{filepath}": filePathWithoutExt,
    "{folder}": folderName,
    "{folderpath}": folderPath,
    "{date}": now.format("YYYYMMDD"),
    "{time}": now.format("HHmmss"),
    "{datetime}": now.format("YYYYMMDD-HHmmss"),
    "{year}": now.format("YYYY"),
    "{month}": now.format("MM"),
    "{day}": now.format("DD")
  };
  for (const [key, value] of Object.entries(variables)) {
    result = result.replace(new RegExp(key.replace(/[{}]/g, "\\$&"), "g"), value);
  }
  result = result.replace(/^\.\//, "").replace(/^\//, "");
  return result;
}
function generateImageFileName(originalName, sourceFile) {
  const now = (0, import_obsidian2.moment)();
  const timestamp = now.format("YYYYMMDDHHmmss");
  const extMatch = originalName.match(/\.[^/.]+$/);
  const ext = extMatch ? extMatch[0] : ".png";
  return `Pasted_${timestamp}_${sourceFile.basename}${ext}`;
}
function getRelativePath(sourcePath, targetPath) {
  const sourceParts = sourcePath.split("/");
  const targetParts = targetPath.split("/");
  sourceParts.pop();
  let commonLength = 0;
  while (commonLength < sourceParts.length && commonLength < targetParts.length && sourceParts[commonLength] === targetParts[commonLength]) {
    commonLength++;
  }
  const upCount = sourceParts.length - commonLength;
  const downParts = targetParts.slice(commonLength);
  const result = [];
  for (let i = 0; i < upCount; i++) {
    result.push("..");
  }
  result.push(...downParts);
  return result.join("/") || ".";
}
function isImagePath(path) {
  const imageExtensions = [".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".svg"];
  const lowerPath = path.toLowerCase();
  return imageExtensions.some((ext) => lowerPath.endsWith(ext));
}
function createMarkdownLink(alt, path, title) {
  if (title) {
    return `![${alt}](${path} "${title}")`;
  }
  return `![${alt}](${path})`;
}
function encodeUrlPath(path) {
  return path.split("/").map((segment) => {
    return encodeURIComponent(segment);
  }).join("/");
}

// main.ts
var ImageMarkdownPastePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    // 用于跟踪文件操作，避免循环触发
    this.isProcessing = false;
    this.renameMap = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ImageMarkdownPasteSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-paste", this.handlePaste.bind(this))
    );
    this.registerEvent(
      this.app.vault.on("rename", this.handleFileRename.bind(this))
    );
    this.registerEvent(
      this.app.vault.on("delete", this.handleFileDelete.bind(this))
    );
    this.addCommand({
      id: "convert-image-references",
      name: "\u8F6C\u6362\u56FE\u7247\u5F15\u7528\u4E3A\u6807\u51C6 Markdown",
      editorCallback: (editor, view) => {
        this.convertImageReferencesInCurrentFile(editor, view);
      }
    });
    this.addCommand({
      id: "organize-images",
      name: "\u6574\u7406\u5F53\u524D\u6587\u6863\u7684\u56FE\u7247\u5230\u914D\u7F6E\u8DEF\u5F84",
      editorCallback: (editor, view) => {
        this.organizeImagesInCurrentFile(view);
      }
    });
    console.log("Image Markdown Paste plugin loaded");
  }
  onunload() {
    console.log("Image Markdown Paste plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 处理粘贴事件
   */
  async handlePaste(evt, editor, view) {
    var _a;
    const files = (_a = evt.clipboardData) == null ? void 0 : _a.files;
    if (!files || files.length === 0)
      return;
    const imageFiles = Array.from(files).filter((file) => file.type.startsWith("image/"));
    if (imageFiles.length === 0)
      return;
    evt.preventDefault();
    const activeFile = view.file;
    if (!activeFile) {
      new import_obsidian3.Notice("\u6CA1\u6709\u6D3B\u52A8\u7684\u6587\u4EF6");
      return;
    }
    for (const imageFile of imageFiles) {
      await this.processPastedImage(imageFile, editor, activeFile);
    }
  }
  /**
   * 处理粘贴的图片
   */
  async processPastedImage(imageFile, editor, sourceFile) {
    try {
      const targetDirPath = parsePathTemplate(this.settings.imageSavePath, sourceFile);
      const imageFileName = generateImageFileName(imageFile.name, sourceFile);
      const targetPath = `${targetDirPath}/${imageFileName}`;
      await this.ensureFolderExists(targetDirPath);
      let finalPath = targetPath;
      let finalFileName = imageFileName;
      if (await this.app.vault.adapter.exists(targetPath)) {
        if (this.settings.autoRenameOnConflict) {
          const extMatch = imageFileName.match(/\.[^/.]+$/);
          const ext = extMatch ? extMatch[0] : "";
          const baseName = imageFileName.replace(/\.[^/.]+$/, "");
          let counter = 1;
          while (await this.app.vault.adapter.exists(`${targetDirPath}/${baseName}_${counter}${ext}`)) {
            counter++;
          }
          finalFileName = `${baseName}_${counter}${ext}`;
          finalPath = `${targetDirPath}/${finalFileName}`;
        } else {
          new import_obsidian3.Notice(`\u6587\u4EF6\u5DF2\u5B58\u5728: ${targetPath}`);
          return;
        }
      }
      const arrayBuffer = await imageFile.arrayBuffer();
      await this.app.vault.adapter.writeBinary(finalPath, arrayBuffer);
      const relativePath = getRelativePath(sourceFile.path, finalPath);
      const encodedPath = encodeUrlPath(relativePath);
      const altText = finalFileName.replace(/\.[^/.]+$/, "");
      let imageLink;
      if (this.settings.useStandardMarkdown) {
        imageLink = createMarkdownLink(altText, encodedPath);
      } else {
        imageLink = `[[${finalPath}|${altText}]]`;
      }
      const cursor = editor.getCursor();
      editor.replaceRange(imageLink, cursor);
      const newPos = {
        line: cursor.line,
        ch: cursor.ch + imageLink.length
      };
      editor.setCursor(newPos);
      new import_obsidian3.Notice(`\u56FE\u7247\u5DF2\u4FDD\u5B58: ${finalPath}`);
    } catch (error) {
      console.error("\u5904\u7406\u7C98\u8D34\u56FE\u7247\u65F6\u51FA\u9519:", error);
      new import_obsidian3.Notice("\u5904\u7406\u7C98\u8D34\u56FE\u7247\u65F6\u51FA\u9519");
    }
  }
  /**
   * 确保文件夹存在
   */
  async ensureFolderExists(path) {
    const parts = path.split("/").filter((p) => p.length > 0);
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const exists = await this.app.vault.adapter.exists(currentPath);
      if (!exists) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  /**
   * 处理文件重命名事件
   */
  async handleFileRename(file, oldPath) {
    var _a, _b;
    if (this.isProcessing)
      return;
    if (!(file instanceof import_obsidian3.TFile))
      return;
    if (!file.extension || file.extension.toLowerCase() !== "md")
      return;
    if (!this.settings.enableRenameSync && !this.settings.enableMoveSync)
      return;
    this.isProcessing = true;
    try {
      const oldFileName = ((_a = oldPath.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/, "")) || "";
      const newFileName = file.basename;
      const oldFolderPath = oldPath.split("/").slice(0, -1).join("/");
      const newFolderPath = ((_b = file.parent) == null ? void 0 : _b.path) || "";
      const isRename = oldFileName !== newFileName;
      const isMove = oldFolderPath !== newFolderPath;
      if (isRename && this.settings.enableRenameSync) {
        await this.handleImageRename(file, oldFileName, newFileName);
      }
      if (isMove && this.settings.enableMoveSync) {
        await this.handleImageMove(file, oldPath, oldFolderPath, newFolderPath);
      }
    } finally {
      this.isProcessing = false;
    }
  }
  /**
   * 处理图片重命名（当文档重命名时）
   */
  async handleImageRename(file, oldFileName, newFileName) {
    var _a;
    const content = await this.app.vault.read(file);
    const imageRefs = this.extractImageReferences(content);
    if (imageRefs.length === 0)
      return;
    let newContent = content;
    let hasChanges = false;
    const processedPaths = /* @__PURE__ */ new Set();
    for (const ref of imageRefs) {
      const oldImagePath = this.resolveImagePath(ref.path, file.path);
      if (!oldImagePath)
        continue;
      if (processedPaths.has(oldImagePath))
        continue;
      processedPaths.add(oldImagePath);
      if (!oldImagePath.includes(oldFileName))
        continue;
      const imageFile = this.app.vault.getAbstractFileByPath(oldImagePath);
      if (!(imageFile instanceof import_obsidian3.TFile))
        continue;
      const newImagePath = oldImagePath.replace(
        new RegExp(oldFileName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g"),
        newFileName
      );
      if (newImagePath === oldImagePath)
        continue;
      try {
        const newParentDir = newImagePath.split("/").slice(0, -1).join("/");
        if (newParentDir) {
          await this.ensureFolderExists(newParentDir);
        }
        await this.app.fileManager.renameFile(imageFile, newImagePath);
        const newRelativePath = getRelativePath(file.path, newImagePath);
        const altText = ((_a = newImagePath.split("/").pop()) == null ? void 0 : _a.replace(/\.[^/.]+$/, "")) || "";
        const oldRelativePath = getRelativePath(file.path, oldImagePath);
        newContent = this.updateAllImageRefs(newContent, oldRelativePath, newRelativePath, altText);
        hasChanges = true;
        console.log(`\u56FE\u7247\u5DF2\u91CD\u547D\u540D: ${oldImagePath} -> ${newImagePath}`);
      } catch (error) {
        console.error(`\u91CD\u547D\u540D\u56FE\u7247\u5931\u8D25: ${oldImagePath}`, error);
      }
    }
    if (hasChanges) {
      await this.app.vault.modify(file, newContent);
      new import_obsidian3.Notice("\u5DF2\u540C\u6B65\u66F4\u65B0\u56FE\u7247\u5F15\u7528");
    }
  }
  /**
   * 更新内容中所有匹配的图片引用
   */
  updateAllImageRefs(content, oldPath, newPath, alt) {
    const encodedOldPath = encodeUrlPath(oldPath);
    const encodedNewPath = encodeUrlPath(newPath);
    let result = content;
    const markdownRegex = new RegExp(
      `!\\[(.*?)\\]\\(${this.escapeRegex(encodedOldPath)}(\\s+".*?")?\\)`,
      "g"
    );
    result = result.replace(markdownRegex, (match, p1, p2) => {
      if (p2) {
        return `![${p1}](${encodedNewPath}${p2})`;
      }
      return `![${p1}](${encodedNewPath})`;
    });
    if (encodedOldPath !== oldPath) {
      const plainMarkdownRegex = new RegExp(
        `!\\[(.*?)\\]\\(${this.escapeRegex(oldPath)}(\\s+".*?")?\\)`,
        "g"
      );
      result = result.replace(plainMarkdownRegex, (match, p1, p2) => {
        if (p2) {
          return `![${p1}](${encodedNewPath}${p2})`;
        }
        return `![${p1}](${encodedNewPath})`;
      });
    }
    const wikiRegex = new RegExp(
      `\\[\\[${this.escapeRegex(oldPath)}(\\|.*?)?\\]\\]`,
      "g"
    );
    result = result.replace(wikiRegex, (match, p1) => {
      if (p1) {
        return `[[${newPath}${p1}]]`;
      }
      return `[[${newPath}]]`;
    });
    return result;
  }
  /**
   * 转义正则表达式特殊字符
   */
  escapeRegex(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  /**
   * 处理图片移动（当文档移动时）
   */
  async handleImageMove(file, oldFilePath, oldFolderPath, newFolderPath) {
    const content = await this.app.vault.read(file);
    const imageRefs = this.extractImageReferences(content);
    let newContent = content;
    let hasChanges = false;
    for (const ref of imageRefs) {
      const oldImagePath = this.resolveImagePath(ref.path, oldFilePath);
      if (oldImagePath) {
        const imageFile = this.app.vault.getAbstractFileByPath(oldImagePath);
        if (imageFile instanceof import_obsidian3.TFile && isImagePath(oldImagePath)) {
          const newTargetDir = parsePathTemplate(this.settings.imageSavePath, file);
          const imageFileName = oldImagePath.split("/").pop() || "";
          const newImagePath = `${newTargetDir}/${imageFileName}`;
          if (newImagePath === oldImagePath)
            continue;
          try {
            await this.ensureFolderExists(newTargetDir);
            await this.app.fileManager.renameFile(imageFile, newImagePath);
            const newRelativePath = getRelativePath(file.path, newImagePath);
            newContent = this.replaceImageReference(
              newContent,
              ref.fullMatch,
              ref.alt || imageFileName.replace(/\.[^/.]+$/, ""),
              newRelativePath
            );
            hasChanges = true;
          } catch (error) {
            console.error(`\u79FB\u52A8\u56FE\u7247\u5931\u8D25: ${oldImagePath}`, error);
          }
        }
      }
    }
    if (hasChanges) {
      await this.app.vault.modify(file, newContent);
      new import_obsidian3.Notice("\u5DF2\u540C\u6B65\u79FB\u52A8\u56FE\u7247\u5230\u65B0\u4F4D\u7F6E");
    }
  }
  /**
   * 提取文档中的所有图片引用
   */
  extractImageReferences(content) {
    const refs = [];
    const wikiLinkRegex = /!\[\[(.+?)(?:\|(.+?))?\]\]/g;
    let match;
    while ((match = wikiLinkRegex.exec(content)) !== null) {
      refs.push({
        fullMatch: match[0],
        path: match[1],
        alt: match[2] || "",
        type: "wikilink"
      });
    }
    const markdownRegex = /!\[(.*?)\]\((.+?)(?:\s+".+?")?\)/g;
    while ((match = markdownRegex.exec(content)) !== null) {
      refs.push({
        fullMatch: match[0],
        alt: match[1],
        path: match[2],
        type: "markdown"
      });
    }
    return refs;
  }
  /**
   * 解析图片路径为绝对路径
   */
  resolveImagePath(imagePath, sourceFilePath) {
    let decodedPath;
    try {
      decodedPath = decodeURIComponent(imagePath);
    } catch (e) {
      decodedPath = imagePath;
    }
    if (decodedPath.startsWith("/")) {
      return decodedPath.slice(1);
    }
    const abstractFile = this.app.vault.getAbstractFileByPath(decodedPath);
    if (abstractFile) {
      return decodedPath;
    }
    const sourceDir = sourceFilePath.split("/").slice(0, -1).join("/");
    if (decodedPath.startsWith("./")) {
      return sourceDir ? `${sourceDir}/${decodedPath.slice(2)}` : decodedPath.slice(2);
    }
    if (decodedPath.startsWith("../")) {
      const parts = decodedPath.split("/");
      let dirParts = sourceDir ? sourceDir.split("/") : [];
      for (const part of parts) {
        if (part === "..") {
          dirParts.pop();
        } else {
          dirParts.push(part);
        }
      }
      return dirParts.join("/");
    }
    return sourceDir ? `${sourceDir}/${decodedPath}` : decodedPath;
  }
  /**
   * 替换图片引用
   */
  replaceImageReference(content, oldRef, alt, newPath) {
    if (this.settings.useStandardMarkdown) {
      const encodedPath = encodeUrlPath(newPath);
      const newRef = createMarkdownLink(alt, encodedPath);
      return content.replace(oldRef, newRef);
    } else {
      const newRef = `[[${newPath}|${alt}]]`;
      return content.replace(oldRef, newRef);
    }
  }
  /**
   * 转换当前文件中的所有图片引用为标准 Markdown
   */
  async convertImageReferencesInCurrentFile(editor, view) {
    var _a;
    const file = view.file;
    if (!file)
      return;
    const content = editor.getValue();
    const imageRefs = this.extractImageReferences(content);
    if (imageRefs.length === 0) {
      new import_obsidian3.Notice("\u672A\u627E\u5230\u56FE\u7247\u5F15\u7528");
      return;
    }
    let newContent = content;
    let convertedCount = 0;
    for (const ref of imageRefs) {
      const absPath = this.resolveImagePath(ref.path, file.path);
      if (absPath) {
        const relativePath = getRelativePath(file.path, absPath);
        const encodedPath = encodeUrlPath(relativePath);
        const alt = ref.alt || ((_a = absPath.split("/").pop()) == null ? void 0 : _a.replace(/\.[^/.]+$/, "")) || "";
        const newRef = createMarkdownLink(alt, encodedPath);
        newContent = newContent.replace(ref.fullMatch, newRef);
        convertedCount++;
      }
    }
    if (convertedCount > 0) {
      editor.setValue(newContent);
      new import_obsidian3.Notice(`\u5DF2\u8F6C\u6362 ${convertedCount} \u4E2A\u56FE\u7247\u5F15\u7528`);
    } else {
      new import_obsidian3.Notice("\u6CA1\u6709\u9700\u8981\u8F6C\u6362\u7684\u56FE\u7247\u5F15\u7528");
    }
  }
  /**
   * 整理当前文档的图片到配置路径
   */
  async organizeImagesInCurrentFile(view) {
    const file = view.file;
    if (!file)
      return;
    const content = await this.app.vault.read(file);
    const imageRefs = this.extractImageReferences(content);
    if (imageRefs.length === 0) {
      new import_obsidian3.Notice("\u672A\u627E\u5230\u56FE\u7247\u5F15\u7528");
      return;
    }
    let newContent = content;
    let movedCount = 0;
    const targetDir = parsePathTemplate(this.settings.imageSavePath, file);
    await this.ensureFolderExists(targetDir);
    for (const ref of imageRefs) {
      const oldImagePath = this.resolveImagePath(ref.path, file.path);
      if (oldImagePath) {
        const imageFile = this.app.vault.getAbstractFileByPath(oldImagePath);
        if (imageFile instanceof import_obsidian3.TFile && isImagePath(oldImagePath)) {
          const imageFileName = oldImagePath.split("/").pop() || "";
          const newImagePath = `${targetDir}/${imageFileName}`;
          if (newImagePath === oldImagePath)
            continue;
          try {
            await this.app.fileManager.renameFile(imageFile, newImagePath);
            const newRelativePath = getRelativePath(file.path, newImagePath);
            const alt = ref.alt || imageFileName.replace(/\.[^/.]+$/, "");
            newContent = this.replaceImageReference(
              newContent,
              ref.fullMatch,
              alt,
              newRelativePath
            );
            movedCount++;
          } catch (error) {
            console.error(`\u79FB\u52A8\u56FE\u7247\u5931\u8D25: ${oldImagePath}`, error);
          }
        }
      }
    }
    if (movedCount > 0) {
      await this.app.vault.modify(file, newContent);
      const editor = view.editor;
      const cursor = editor.getCursor();
      editor.setValue(newContent);
      editor.setCursor(cursor);
      new import_obsidian3.Notice(`\u5DF2\u6574\u7406 ${movedCount} \u5F20\u56FE\u7247\u5230 ${targetDir}`);
    } else {
      new import_obsidian3.Notice("\u6CA1\u6709\u9700\u8981\u6574\u7406\u7684\u56FE\u7247");
    }
  }
  /**
   * 处理文件删除事件
   */
  async handleFileDelete(file) {
  }
};
